name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: wasm-pack build --target nodejs

      - run: wasm-pack test --node

      - run: cargo check
      - run: cargo check --target wasm32-unknown-unknown
      - run: cargo check --no-default-features
      - run: cargo check --target wasm32-unknown-unknown --no-default-features
      - run: cargo check --no-default-features --features console_error_panic_hook
      - run: cargo check --target wasm32-unknown-unknown --no-default-features --features console_error_panic_hook
      # - run: cargo check                                 --no-default-features --features "console_error_panic_hook wee_alloc"
      # - run: cargo check --target wasm32-unknown-unknown --no-default-features --features "console_error_panic_hook wee_alloc"

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        run: rustup update stable

      - uses: Swatinem/rust-cache@v1

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run
        run: cargo fmt --all -- --check
